version: '3.8'

services:
  # Go app service
  app:
    build: .
    container_name: crm-app
    ports:
      - "8081:8081"  # Exposing port 8081 for your Go app
    depends_on:
      - db  # Ensure db service is available before starting the app
    environment:
      - DB_HOST=db  # Connect to PostgreSQL container (service name is "db")
      - DB_USER=crm_user
      - DB_PASSWORD=password
      - DB_NAME=crm
      - DB_PORT=5432  # PostgreSQL default port

  # PostgreSQL service
  db:
    image: postgres:13-alpine
    container_name: crm-db
    environment:
      POSTGRES_USER: crm_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crm
    ports:
      - "5432:5432"  # Expose PostgreSQL port
    volumes:
      - crm-db-data:/var/lib/postgresql/data  # Persist data across container restarts

volumes:
  crm-db-data:
    driver: local
